services:
  llumen:
    image: ghcr.io/pinkfuwa/llumen:latest
    # build:
    #   context: .
    #   dockerfile: ./package/Dockerfile
    restart: on-failure:3
    environment:
      - "API_KEY=sk-or-<YOUR_API_KEY>"
    volumes:
      - "./data:/data"
    ports:
      - "3000:80"
    deploy:
      resources:
        limits:
          memory: 1G
    memswap_limit: 1G
