services:
  llumen:
    image: ghcr.io/pinkfuwa/llumen:nightly
    restart: on-failure:4
    environment:
      - "API_KEY=sk-or-v1-openrouter-api-key"
    volumes:
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llumen.rule=Host(`llumen.example.com`)"
      - "traefik.http.services.llumen.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          memory: 512M
    memswap_limit: 512M
