[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.141"
typeshare = "1.0.4"

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.sea-orm]
version = "1.1.14"
default-features = false
features = ["macros"]
